workflow test

diff --git a/.github/workflows/Tests.yml b/.github/workflows/Tests.yml
--- a/.github/workflows/Tests.yml
+++ b/.github/workflows/Tests.yml
@@ -11,7 +11,7 @@ jobs:
 
     macOS-swift-53:
         name: macOS (Swift 5.3)
-        runs-on: macOS-latest
+        runs-on: macos-latest
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -19,7 +19,60 @@ jobs:
           run: mkdir logs
         - name: Xcode Version
           run: |
+            ls /Applications/Xcode*
             sudo xcode-select -s /Applications/Xcode_12.3.app
+            xcodebuild -version
+            swift --version
+        - name: Swift Version
+          run: swift --version
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    macOS-swift-54:
+        name: macOS (Swift 5.4)
+        runs-on: macos-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Xcode Version
+          run: |
+            ls /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_12.5.1.app
+            xcodebuild -version
+            swift --version
+        - name: Swift Version
+          run: swift --version
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    macOS-swift-55:
+        name: macOS (Swift 5.5)
+        runs-on: macos-11
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Xcode Version
+          run: |
+            ls /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.0.app
             xcodebuild -version
             swift --version
         - name: Swift Version
@@ -36,9 +89,9 @@ jobs:
 
     macOS-swift-nightly:
         name: macOS (Swift Development Nightly)
-        runs-on: macOS-latest
         env:
             TOOLCHAINS: swift
+        runs-on: macos-11
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -56,6 +109,7 @@ jobs:
             wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
             sudo installer -pkg $downloadYML-osx.pkg -target /
             ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            ls /Applications/Xcode*
             sudo xcode-select -s /Applications/Xcode_13.0.app
             swift --version
         - name: Xcode Version
@@ -78,6 +132,48 @@ jobs:
         name: Linux (Swift 5.3)
         runs-on: ubuntu-18.04
         container: swift:5.3.3-bionic
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Swift Version
+          run: swift --version
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    linux-swift-54:
+        name: Linux (Swift 5.4)
+        runs-on: ubuntu-18.04
+        container: swift:5.4.2-bionic
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Swift Version
+          run: swift --version
+        - name: Test (Release)
+          run: swift test --configuration release -Xswiftc -enable-testing --enable-test-discovery
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    linux-swift-55:
+        name: Linux (Swift 5.5)
+        runs-on: ubuntu-18.04
+        container: swiftlang/swift:nightly-5.5-bionic
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -118,7 +214,7 @@ jobs:
 
     xcode-swift-53:
         name: Xcode (Swift 5.3)
-        runs-on: macOS-latest
+        runs-on: macos-latest
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -126,7 +222,188 @@ jobs:
           run: mkdir logs
         - name: Xcode Version
           run: |
+            ls /Applications/Xcode*
             sudo xcode-select -s /Applications/Xcode_12.3.app
+            xcodebuild -version
+            swift --version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="CollectionExtensions.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep CollectionExtensions-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="CollectionExtensions-Package"
+            else
+            SCHEME="CollectionExtensions"
+            fi
+            else
+            SCHEME="CollectionExtensions-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Test (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="CollectionExtensions.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep CollectionExtensions-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="CollectionExtensions-Package"
+            else
+            SCHEME="CollectionExtensions"
+            fi
+            else
+            SCHEME="CollectionExtensions-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Test (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (watchOS)
+          run: |
+            WORKSPACE="CollectionExtensions.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep CollectionExtensions-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="CollectionExtensions-Package"
+            else
+            SCHEME="CollectionExtensions"
+            fi
+            else
+            SCHEME="CollectionExtensions-watchOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (watchOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    xcode-swift-54:
+        name: Xcode (Swift 5.4)
+        runs-on: macos-latest
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Xcode Version
+          run: |
+            ls /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_12.5.1.app
+            xcodebuild -version
+            swift --version
+        - name: XC Pretty
+          run: sudo gem install xcpretty-travis-formatter
+        - name: Detect Workspace & Scheme (iOS)
+          run: |
+            WORKSPACE="CollectionExtensions.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep CollectionExtensions-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="CollectionExtensions-Package"
+            else
+            SCHEME="CollectionExtensions"
+            fi
+            else
+            SCHEME="CollectionExtensions-iOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Test (iOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=iPhone 11" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-iOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (tvOS)
+          run: |
+            WORKSPACE="CollectionExtensions.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep CollectionExtensions-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="CollectionExtensions-Package"
+            else
+            SCHEME="CollectionExtensions"
+            fi
+            else
+            SCHEME="CollectionExtensions-tvOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Test (tvOS Release)
+          run: |
+            source "setup.sh"
+            echo "Testing workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild test -workspace "$WORKSPACE" -scheme "$SCHEME" -destination "name=Apple TV" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-tvOS-test-release.log | xcpretty
+        - name: Detect Workspace & Scheme (watchOS)
+          run: |
+            WORKSPACE="CollectionExtensions.xcworkspace"
+            if [[ ! -e "$WORKSPACE" ]]
+            then
+            WORKSPACE="."
+            GOTPACKAGE=$(xcodebuild -workspace . -list | (grep CollectionExtensions-Package || true))
+            if [[ $GOTPACKAGE != "" ]]
+            then
+            SCHEME="CollectionExtensions-Package"
+            else
+            SCHEME="CollectionExtensions"
+            fi
+            else
+            SCHEME="CollectionExtensions-watchOS"
+            fi
+            echo "set -o pipefail; export PATH='swift-latest:$PATH'; WORKSPACE='$WORKSPACE'; SCHEME='$SCHEME'" > setup.sh
+        - name: Build (watchOS Release)
+          run: |
+            source "setup.sh"
+            echo "Building workspace $WORKSPACE scheme $SCHEME."
+            xcodebuild clean build -workspace "$WORKSPACE" -scheme "$SCHEME" -configuration Release CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ENABLE_TESTABILITY=YES | tee logs/xcodebuild-watchOS-build-release.log | xcpretty
+        - name: Upload Logs
+          uses: actions/upload-artifact@v1
+          if: always()
+          with:
+            name: logs
+            path: logs
+
+
+    xcode-swift-55:
+        name: Xcode (Swift 5.5)
+        runs-on: macos-11
+        steps:
+        - name: Checkout
+          uses: actions/checkout@v1
+        - name: Make Logs Directory
+          run: mkdir logs
+        - name: Xcode Version
+          run: |
+            ls /Applications/Xcode*
+            sudo xcode-select -s /Applications/Xcode_13.0.app
             xcodebuild -version
             swift --version
         - name: XC Pretty
@@ -207,9 +484,9 @@ jobs:
 
     xcode-swift-nightly:
         name: Xcode (Swift Development Nightly)
-        runs-on: macOS-latest
         env:
             TOOLCHAINS: swift
+        runs-on: macos-11
         steps:
         - name: Checkout
           uses: actions/checkout@v1
@@ -227,6 +504,7 @@ jobs:
             wget --quiet https://swift.org/builds/$branch/xcode/$downloadYML/$downloadYML-osx.pkg
             sudo installer -pkg $downloadYML-osx.pkg -target /
             ln -s "/Library/Developer/Toolchains/$downloadYML.xctoolchain/usr/bin" swift-latest
+            ls /Applications/Xcode*
             sudo xcode-select -s /Applications/Xcode_13.0.app
             swift --version
         - name: Xcode Version
